

import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "BackHack.dev",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"antialiased font-sans"}>
        <div className="flex min-h-screen  flex-col bg-slate-50 text-base font-normal text-black w-full">

          <Header />
          <div className="flex-grow">
            {children}
          </div>
          <Footer/>

        </div>

      </body>
    </html>
  );
}
